In [1]:
# Linear Algebra. Lesson 05 Task (https://gb.ru/lessons/229662/homework). SVD, martix

# Task1. Find with NumPy SVD for the matrix

import numpy as np
np.set_printoptions(precision=2, suppress=True)

A = np.array([
              [1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]
            ])

U, s, W = np.linalg.svd(A) # where s - diagonal elements

V = W.T

D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s # -> Diaggonal  matrix

print(f'Матрица D:\n{D}')
print(f'Матрица U:\n{U}')
print(f'Матрица V:\n{V}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [2]:
# Task2. Find with NumPy Euclidean and Frobenius norms for the matrix

# Euclidean 
np.linalg.norm(A, ord=2)


8.824868854820444

In [3]:
# Frobenius
np.linalg.norm(A, ord='fro')

11.045361017187261